### ISSUE TITLE
Parser to parse tag

### ISSUE THREAD

**Issue by VerbalCriminal** [cs2103jan2016-W14-2J/main#74]
ensure that users can add a tag with spacing in between

**Comment by yanglu758** [comment]
BUG: tag 1 <tag>
`Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "1 <tag>"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at Parser.Parser.setTaskIndex(Parser.java:233)
    at Parser.Parser.executeCommand(Parser.java:114)
    at Parser.Parser.<init>(Parser.java:55)`

**Comment by yanglu758** [comment]
BUG: tag 1 {tag}
(ignore the curly bracket, i cannot write < here)
`NumberFormatException`

**Comment by VerbalCriminal** [comment]
There is no bug for this command. You probably used the wrong getters.
to get commandtype, use getCommandType()
to get taskID, use getTaskID();
to get tag, use getTag();
