### ISSUE TITLE
Parser to fix bugs

### ISSUE THREAD

**Issue by yanglu758** [cs2103jan2016-W14-2J/main#92]
Currently detected:

1) adddddd, add1, add2 etc: 
`Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 1
    at Parser.Parser.getUserInputContent(Parser.java:164)
    at Parser.Parser.processUserInput(Parser.java:124)
    at Parser.Parser.executeCommand(Parser.java:75)
    at Parser.Parser.<init>(Parser.java:48)`

**Comment by yanglu758** [comment]
2) add 1

Parsed as overdue task with 1pm deadline
Supposedly should be parsed with floating task with name "1"

**Comment by yanglu758** [comment]
Too sensitive to standalone integer

e.g. {CS2105} Assignment 2 Networking
parsed as 
tag: CS2105 - correct
name: Assignment Networking - wrong
deadline: today 2am - wrong
